version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nodejs_tutorial
      POSTGRES_PASSWORD: nodejs_tutorial
      POSTGRES_DB: nodejs_tutorial
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: node:20
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    ports:
      - "3000:3000"
    environment:
      DB_HOST: nodejs_tutorial-db-1
      DB_USER: nodejs_tutorial
      DB_PASS: nodejs_tutorial
      DB_NAME: nodejs_tutorial
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data:
